### ISSUE TITLE
Missing WebHookServer causes panic

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-worker#272]
with no webHookServer config:

```
<13>May  9 08:42:44 taskcluster-worker: time="2017-05-09T08:43:15-07:00" level=info msg="done processing task" prefix=worker runId=0 taskId=QJv6JrK-RKOpXfI1vqXJgw 
<13>May  9 08:42:44 taskcluster-worker: panic: taskrun: Options.Environment.WebHookServer is nil
<13>May  9 08:42:44 taskcluster-worker: 
<13>May  9 08:42:44 taskcluster-worker: goroutine 82 [running]:
<13>May  9 08:42:44 taskcluster-worker: github.com/taskcluster/taskcluster-worker/worker/taskrun.(*Options).mustBeValid(0xc420467908)
<13>May  9 08:42:44 taskcluster-worker:         /home/travis/gopath/src/github.com/taskcluster/taskcluster-worker/worker/taskrun/options.go:34 +0x32e
<13>May  9 08:42:44 taskcluster-worker: github.com/taskcluster/taskcluster-worker/worker/taskrun.New(0xe3cd20, 0xc4200fd280, 0x7f04746ce1b0, 0xc420248c40, 0x0, 0x0, 0xe481e0, 0xc4202ea630, 0xe3cce0, 0xc4203baf68, ...)
<13>May  9 08:42:44 taskcluster-worker:         /home/travis/gopath/src/github.com/taskcluster/taskcluster-worker/worker/taskrun/taskrun.go:55 +0x40
<13>May  9 08:42:44 taskcluster-worker: github.com/taskcluster/taskcluster-worker/worker.(*Worker).processClaim(0xc4203baf00, 0xc4202249c0, 0x2b, 0xc4203282c0, 0x143, 0xc420224990, 0x27, 0x0, 0xed0a3e89a, 0x2bcf35c0, ...)
<13>May  9 08:42:44 taskcluster-worker:         /home/travis/gopath/src/github.com/taskcluster/taskcluster-worker/worker/worker.go:339 +0x881
<13>May  9 08:42:44 taskcluster-worker: created by github.com/taskcluster/taskcluster-worker/worker.(*Worker).Start
<13>May  9 08:42:44 taskcluster-worker:         /home/travis/gopath/src/github.com/taskcluster/taskcluster-worker/worker/worker.go:212 +0x5a8
```

**Comment by ckousik** [comment]
@djmitche What was the provider for webhookServer?

**Comment by djmitche** [comment]
I'm not sure what you mean by provider.  It's not a plugin, it's part of the runtime (https://github.com/taskcluster/taskcluster-worker/blob/33dcf70a1e4e4bc7bf758b868d474353f644570c/runtime/webhookserver/doc.go).
